version: '3.9'
services:
    webserver:
        container_name: webserver
        image: nginx:1.27
        volumes:
            - ./backend:/var/www/html/backend
            - ./docker/nginx/back.conf:/etc/nginx/nginx.conf
        ports:
            - ${NGINX_PORT}:80
        networks:
            - symfony_app
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - APP_ENV=${APP_ENV}
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./backend:/var/www/html/backend
        networks:
            - symfony_app
        depends_on:
            - db
            - webserver
    db:
        container_name: db
        image: mysql:8.0
        restart: always
        volumes:
            - ./volumes/mysql:/var/lib/mysql
            - ./volumes/init-db:/docker-entrypoint-initdb.d
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - symfony_app
        depends_on:
            - webserver
volumes:
    db_data:
networks:
    symfony_app: